---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name:
      local_action:
        module: git
        repo: git://syellayi023/ansible.git
        dest: /tmp/test
        
       
     - name:
       command: sh /tmp/test/test.sh
       delegate_to: 127.0.0.1
     
    
      
      
      
        
      
        
