---
- hosts: 127.0.0.1
  connection: local
  tasks:
  
    - name: copy the file
      become: true  
      copy:
        src: test.sh
        dest: :/tmp/test
        remote_src: yes
        
       
    - name: execute the script
      shell: /tmp/test/test.sh
      delegate_to: 127.0.0.1
      ignore_errors: true
     
    
      
      
      
        
      
        
